# Generated by Django 4.2.16 on 2024-10-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_tag_remove_blogpost_comment_count_blogpost_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
