# Generated by Django 5.1.1 on 2024-10-27 00:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(upload_to="blogs/"),
        ),
    ]
