# Generated by Django 5.1.1 on 2024-10-12 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="created_at",
            new_name="order_date",
        ),
    ]
