# Generated by Django 5.1.1 on 2024-10-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_tag_remove_product_tags_product_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="new_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="old_price",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
