# Generated by Django 5.1.1 on 2024-10-16 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_order_quantity_order_entreprise_order_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="products.category",
            ),
        ),
    ]
