# Generated by Django 5.1.1 on 2024-10-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_tag_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="brands/"),
        ),
    ]
