# Generated by Django 5.1.1 on 2024-10-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_order_product_alter_order_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
    ]
