# Generated by Django 5.1.1 on 2024-11-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_product_emballage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="emballage",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
    ]
