# Generated by Django 4.2.16 on 2024-11-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_product_description_alter_product_emballage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity_in_stock",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
