# Generated by Django 4.2.16 on 2024-11-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_alter_product_quantity_in_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("phone1", models.CharField(max_length=20)),
                ("phone2", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="team_photos/"),
                ),
                ("priority", models.IntegerField(default=0)),
            ],
        ),
    ]
