# Generated by Django 4.2.16 on 2024-11-09 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_teammember"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "ordering": ["priority", "name"],
                "verbose_name": "Membre de l'équipe",
                "verbose_name_plural": "Membres de l'équipe",
            },
        ),
    ]
