# Generated by Django 4.2.16 on 2024-11-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_alter_teammember_email_alter_teammember_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="priority",
            field=models.IntegerField(),
        ),
    ]
